import { readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { topIssues } from '../triage.js';
import type { AuditResults, FileContext, Fix, Framework, StackInfo } from '../types.js';

const PROMPTS_DIR = join(dirname(fileURLToPath(import.meta.url)), 'prompts');

function loadPrompt(name: string): string {
  try {
    return readFileSync(join(PROMPTS_DIR, name), 'utf8');
  } catch {
    return '';
  }
}

function frameworkPromptFile(framework: Framework): string {
  switch (framework) {
    case 'nextjs':
      return 'nextjs.md';
    case 'astro':
      return 'astro.md';
    case 'remix':
      return 'remix.md';
    case 'vite':
      return 'vite.md';
    default:
      return 'generic.md';
  }
}

/** Framework-aware engineer instructions for an IDE agent that will apply fixes. */
export function buildInstructions(framework: Framework): string {
  const intro = loadPrompt('brief-intro.md');
  const fw = loadPrompt(frameworkPromptFile(framework));
  return fw ? `${intro}\n\n---\n\n${fw}` : intro;
}

/** Render the audit findings as readable markdown (not JSON dump). */
function renderFindings(audits: AuditResults): string {
  const parts: string[] = [];

  if (audits.lighthouse) {
    const lh = audits.lighthouse;
    parts.push('## Lighthouse');
    parts.push(
      `- URL: ${lh.url} (${lh.device})`,
      `- Scores: perf ${lh.scores.performance}, a11y ${lh.scores.accessibility}, seo ${lh.scores.seo}, best-practices ${lh.scores.bestPractices}`,
      `- Metrics: LCP ${Math.round(lh.metrics.lcp)}ms, FCP ${Math.round(lh.metrics.fcp)}ms, TBT ${Math.round(lh.metrics.tbt)}ms, CLS ${lh.metrics.cls.toFixed(3)}`,
      '',
      'Top failing audits (by impact × fixability):',
    );
    for (const a of topIssues(lh.failingAudits, 8)) {
      parts.push(`- **${a.title}** (${a.id}) — score ${(a.score * 100).toFixed(0)}${a.displayValue ? `, ${a.displayValue}` : ''}`);
    }
    parts.push('');
  }

  if (audits.bundle) {
    const b = audits.bundle;
    const measured = b.source === 'next-manifest' || b.source === 'dist-scan';
    parts.push('## Bundle');
    if (measured) {
      parts.push(`- Built JS: ${Math.round(b.totalEstimatedSize / 1024)}KB (measured from ${b.source})`);
    } else {
      parts.push(
        `- Worst-case dependency size: ~${Math.round(b.totalEstimatedSize / 1024)}KB (estimated — no build output found).`,
        '  This is an upper bound from full-package sizes, NOT the shipped bundle. Run a production build for real numbers.',
      );
    }
    if (b.heavyDeps.length) {
      parts.push('- Heavy dependencies (worst-case full-import size — tree-shakeable libs ship less):');
      for (const d of b.heavyDeps) parts.push(`  - ${d.name} (~${Math.round(d.estimatedSize / 1024)}KB)`);
    }
    if (b.duplicateDeps.length) {
      parts.push(
        '- Duplicate installed versions (from node_modules — many are build/CLI tooling that never reaches the client bundle; verify before acting):',
      );
      for (const d of b.duplicateDeps) parts.push(`  - ${d.name}: ${d.versions.join(', ')}`);
    }
    if (b.recommendations.length) {
      parts.push('- Suggested substitutions:');
      for (const r of b.recommendations) parts.push(`  - ${r}`);
    }
    parts.push('');
  }

  if (audits.deadcode) {
    const d = audits.deadcode;
    parts.push('## Dead code');
    if (d.unlisted.length) {
      parts.push(
        `- ⚠ Unlisted dependencies (imported but missing from package.json — can crash a clean install): ${d.unlisted.join(', ')}`,
      );
    }
    if (d.unusedDependencies.length) parts.push(`- Unused dependencies: ${d.unusedDependencies.join(', ')}`);
    if (d.unusedExports.length) {
      parts.push('- Unused exports (may still be used by tests, dynamic imports, or a dispatcher — verify each before deleting):');
      for (const e of d.unusedExports.slice(0, 25)) parts.push(`  - ${e.file} → ${e.name}`);
    }
    if (d.unusedFiles.length) {
      parts.push(`- Unused files${d.truncatedFiles ? ' (truncated — likely a misconfigured entry point)' : ''}:`);
      for (const f of d.unusedFiles) parts.push(`  - ${f}`);
    }
    parts.push(`- Confidence: ${d.confidence}`);
    parts.push('');
  }

  return parts.join('\n');
}

export interface BriefInput {
  audits: AuditResults;
  stack: StackInfo;
  fileContext?: FileContext[];
  /** Deterministic fixes already produced by the tool (listed so the LLM skips them). */
  ruleFixes?: Fix[];
  url?: string;
  localPath?: string;
}

/**
 * Build a self-contained markdown brief the user can hand to any IDE/agent LLM
 * (Claude Code, Cursor, …) — or that the MCP host model receives — so it can
 * apply the contextual code fixes. No external API is involved.
 */
export function buildFixBrief(input: BriefInput): string {
  const { audits, stack } = input;
  const md: string[] = [];

  md.push('# perfpatch — fix brief');
  md.push('');
  md.push('_Generated by perfpatch. Paste this into your IDE agent (Claude Code, Cursor, …) and let it apply the fixes, or use the perfpatch MCP server._');
  md.push('');

  md.push(buildInstructions(stack.framework));
  md.push('');
  md.push('---');
  md.push('');

  md.push('## Stack');
  md.push(
    `- Framework: ${stack.framework}${stack.frameworkVersion ? ` ${stack.frameworkVersion}` : ''}`,
    `- Bundler: ${stack.bundler} · CSS: ${stack.cssApproach} · Images: ${stack.imageLib}`,
    `- ${stack.typescript ? 'TypeScript' : 'JavaScript'} · ${stack.packageManager} · Node ${stack.nodeVersion}`,
  );
  if (input.url) md.push(`- Audited URL: ${input.url}`);
  if (input.localPath) md.push(`- Project: ${input.localPath}`);
  md.push('');

  md.push(renderFindings(audits));

  if (input.ruleFixes && input.ruleFixes.length > 0) {
    md.push('## Already handled by perfpatch (deterministic — skip these)');
    for (const f of input.ruleFixes) {
      md.push(`- ${f.title}${f.command ? ` → \`${f.command}\`` : ''}`);
    }
    md.push('');
  }

  if (input.fileContext && input.fileContext.length > 0) {
    md.push('## Relevant file contents (partial)');
    for (const fc of input.fileContext) {
      md.push('', `### ${fc.path}`, '```', fc.content, '```');
    }
    md.push('');
  }

  md.push('---');
  md.push('');
  md.push('When done, re-run `perfpatch` (or the MCP `verify_fix` tool) to confirm the metrics improved.');

  return md.join('\n');
}
